language: java

jdk:
  - openjdk14

sudo: false

env:
  global:
    - CODECOV_TOKEN="c29f8ed0-5608-460b-973d-3e1fb5c94f15"

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - malgin.zhenya@yandex.ru
    on_success: never # default: change
    on_failure: always # default: always